CREATE TABLE PROJECT (
    ProjectID NUMBER(5)  PRIMARY KEY,
    ProjectName VARCHAR2(50) NOT NULL,
    ClientName VARCHAR2(20),
    Budget NUMBER(10, 2),
    StartDate DATE DEFAULT SYSDATE
);
CREATE TABLE FABRIC (
    SwatchID NUMBER(5) CONSTRAINT Swatch_id_pk PRIMARY KEY,
    MaterialType VARCHAR2(50) NOT NULL,
    ColorCode VARCHAR2(50)
);
CREATE TABLE CONTRACTOR (
    ContractorID NUMBER(5) CONSTRAINT cont_id_pk PRIMARY KEY,
    FName VARCHAR2(20) NOT NULL,
    LName VARCHAR2(20) NOT NULL,
    Specialty VARCHAR2(50)
);
CREATE TABLE FURNITURE (
    SKU VARCHAR2(20) CONSTRAINT sku_pk PRIMARY KEY,
    Description VARCHAR2(200),
    Price NUMBER(8, 2),
    SwatchID NUMBER(5),
    CONSTRAINT Swatch_id_fk FOREIGN KEY (SwatchID) 
        REFERENCES FABRIC (SwatchID)
);
CREATE TABLE CONTRACTOR_PHONE (
    ContractorID NUMBER(5),
    Phone VARCHAR2(20),
    CONSTRAINT phone_pk PRIMARY KEY (ContractorID, Phone),
    CONSTRAINT phone_cont_fk FOREIGN KEY (ContractorID) 
        REFERENCES CONTRACTOR (ContractorID)
);
CREATE TABLE SCHEDULE (
    TaskID NUMBER(5),
    ProjectID NUMBER(5),
    TaskDescription VARCHAR2(200),
    TaskDate DATE,
    Status VARCHAR2(20),
    ContractorID NUMBER(5),
    CONSTRAINT sched_pk PRIMARY KEY (TaskID, ProjectID),
    CONSTRAINT sched_proj_fk FOREIGN KEY (ProjectID) 
        REFERENCES PROJECT (ProjectID),
    CONSTRAINT sched_cont_fk FOREIGN KEY (ContractorID) 
        REFERENCES CONTRACTOR (ContractorID)
);
CREATE TABLE PROJECT_FURNITURE (
    ProjectID NUMBER(5),
    SKU VARCHAR2(20),
    Quantity NUMBER(3) CONSTRAINT Quantity_check CHECK (Quantity > 0),
    CONSTRAINT pf_pk PRIMARY KEY (ProjectID, SKU),
    CONSTRAINT pf_proj_fk FOREIGN KEY (ProjectID) 
        REFERENCES PROJECT (ProjectID),
    CONSTRAINT pf_sku_fk FOREIGN KEY (SKU) 
        REFERENCES FURNITURE (SKU)
);
CREATE TABLE PROJECT_CONTRACTOR (
    ProjectID NUMBER(5),
    ContractorID NUMBER(5),
    WorkHours NUMBER(5, 2),
    CONSTRAINT pc_pk PRIMARY KEY (ProjectID, ContractorID),
    CONSTRAINT pc_proj_fk FOREIGN KEY (ProjectID) 
        REFERENCES PROJECT (ProjectID),
    CONSTRAINT pc_cont_fk FOREIGN KEY (ContractorID) 
        REFERENCES CONTRACTOR (ContractorID)
);

***************************************************************
INSERT INTO PROJECT VALUES (101, 'Modern Villa', 'Ahmed', 150000.00, TO_DATE('10-01-2026', 'DD-MM-YYYY'));
INSERT INTO PROJECT VALUES (102, 'Office Renovation', 'Mona', 75000.00, TO_DATE('15-02-2026', 'DD-MM-YYYY'));
INSERT INTO PROJECT VALUES (103, 'Classic Apartment', 'Ahmed', 150000.00, TO_DATE('20-03-2026', 'DD-MM-YYYY'));
INSERT INTO PROJECT VALUES (104, 'Clinic Design', 'Khaled', 120000.00, TO_DATE('05-04-2026', 'DD-MM-YYYY'));
INSERT INTO PROJECT VALUES (105, 'Restaurant Setup', 'Tarek', 250000.00, TO_DATE('11-05-2026', 'DD-MM-YYYY'));
INSERT INTO PROJECT VALUES (106, 'Smart Home', 'Salma', 180000.00, TO_DATE('01-06-2026', 'DD-MM-YYYY'));
INSERT INTO PROJECT VALUES (107, 'Studio Layout', 'Youssef', 40000.00, TO_DATE('15-07-2026', 'DD-MM-YYYY'));
INSERT INTO PROJECT VALUES (108, 'Retail Shop', 'Nour', 95000.00, TO_DATE('10-08-2026', 'DD-MM-YYYY'));
INSERT INTO PROJECT VALUES (109, 'Duplex Villa', 'Hassan', 210000.00, TO_DATE('22-09-2026', 'DD-MM-YYYY'));
INSERT INTO PROJECT VALUES (110, 'Roof Garden', 'Sara', 55000.00, TO_DATE('30-10-2026', 'DD-MM-YYYY'));

INSERT INTO FABRIC VALUES (1, 'Cotton', 'Red');
INSERT INTO FABRIC VALUES (2, 'Cotton', 'Blue'); 
INSERT INTO FABRIC VALUES (3, 'Velvet', 'Black');
INSERT INTO FABRIC VALUES (4, 'Leather', 'Black');
INSERT INTO FABRIC VALUES (5, 'Wool', 'Grey');
INSERT INTO FABRIC VALUES (6, 'Linen', 'White');
INSERT INTO FABRIC VALUES (7, 'Polyester', 'Grey');
INSERT INTO FABRIC VALUES (8, 'Satin', 'Gold');
INSERT INTO FABRIC VALUES (9, 'Chiffon', 'Pink');
INSERT INTO FABRIC VALUES (10, 'Denim', 'Navy');


INSERT INTO CONTRACTOR VALUES (1, 'Ibrahim', 'Mahmoud', 'Painter');
INSERT INTO CONTRACTOR VALUES (2, 'Samar', 'Mohamed', 'Painter'); 
INSERT INTO CONTRACTOR VALUES (3, 'Ibrahim', 'Mahmoud', 'Electrician');
INSERT INTO CONTRACTOR VALUES (4, 'Mostafa', 'Kamal', 'Plumber');
INSERT INTO CONTRACTOR VALUES (5, 'Abdelrahman', 'Ali', 'Flooring');
INSERT INTO CONTRACTOR VALUES (6, 'Tamer', 'Ali', 'HVAC');
INSERT INTO CONTRACTOR VALUES (7, 'Amr', 'Wagdy', 'Decorator');
INSERT INTO CONTRACTOR VALUES (8, 'Ramy', 'Diab', 'Glass Worker');
INSERT INTO CONTRACTOR VALUES (9, 'Mohamed', 'Said', 'Electrician'); 
INSERT INTO CONTRACTOR VALUES (10, 'Ayman', 'Wagdy', 'Gypsum Board');

INSERT INTO FURNITURE VALUES ('CHR-001', 'Dining Chair', 1500.00, 1);
INSERT INTO FURNITURE VALUES ('CHR-002', 'Dining Chair', 1800.00, 2); 
INSERT INTO FURNITURE VALUES ('TBL-001', 'Glass Table', 4500.00, 1); 
INSERT INTO FURNITURE VALUES ('BED-001', 'King Size Bed', 12000.00, 4);
INSERT INTO FURNITURE VALUES ('DSK-001', 'Office Desk', 3500.00, 5);
INSERT INTO FURNITURE VALUES ('CAB-001', 'Kitchen Cabinet', 6000.00, 6);
INSERT INTO FURNITURE VALUES ('RUG-001', 'Persian Rug', 2500.00, 7);
INSERT INTO FURNITURE VALUES ('LMP-001', 'Floor Lamp', 1200.00, 8);
INSERT INTO FURNITURE VALUES ('MIR-001', 'Wall Mirror', 800.00, 9);
INSERT INTO FURNITURE VALUES ('SOF-003', 'Armchair', 2200.00, 10);

INSERT INTO CONTRACTOR_PHONE VALUES (1, '01011111111');
INSERT INTO CONTRACTOR_PHONE VALUES (1, '01022222222'); 
INSERT INTO CONTRACTOR_PHONE VALUES (2, '01033333333');
INSERT INTO CONTRACTOR_PHONE VALUES (3, '01044444444');
INSERT INTO CONTRACTOR_PHONE VALUES (4, '01055555555');
INSERT INTO CONTRACTOR_PHONE VALUES (5, '01066666666');
INSERT INTO CONTRACTOR_PHONE VALUES (6, '01077777777');
INSERT INTO CONTRACTOR_PHONE VALUES (7, '01088888888');
INSERT INTO CONTRACTOR_PHONE VALUES (8, '01099999999');
INSERT INTO CONTRACTOR_PHONE VALUES (9, '01100000000');


INSERT INTO SCHEDULE VALUES (1, 101, 'Wood Painting', TO_DATE('15-01-2026', 'DD-MM-YYYY'), 'Done', 1);
INSERT INTO SCHEDULE VALUES (2, 101, 'Wall Painting', TO_DATE('20-01-2026', 'DD-MM-YYYY'), 'Pending', 2);
INSERT INTO SCHEDULE VALUES (1, 102, 'Office Painting', TO_DATE('20-02-2026', 'DD-MM-YYYY'), 'Done', 1);
INSERT INTO SCHEDULE VALUES (2, 102, 'Wiring', TO_DATE('25-02-2026', 'DD-MM-YYYY'), 'In Progress', 3);
INSERT INTO SCHEDULE VALUES (1, 103, 'Piping', TO_DATE('25-03-2026', 'DD-MM-YYYY'), 'Pending', 4);
INSERT INTO SCHEDULE VALUES (1, 104, 'Ceramic Installation', TO_DATE('10-04-2026', 'DD-MM-YYYY'), 'Done', 5);
INSERT INTO SCHEDULE VALUES (1, 105, 'AC Setup', TO_DATE('15-05-2026', 'DD-MM-YYYY'), 'Pending', 6);
INSERT INTO SCHEDULE VALUES (1, 106, 'Decor Setup', TO_DATE('10-06-2026', 'DD-MM-YYYY'), 'In Progress', 7);
INSERT INTO SCHEDULE VALUES (1, 107, 'Window Fixing', TO_DATE('20-07-2026', 'DD-MM-YYYY'), 'Done', 8);
INSERT INTO SCHEDULE VALUES (1, 108, 'Network Setup', TO_DATE('15-08-2026', 'DD-MM-YYYY'), 'Pending', 9);

INSERT INTO PROJECT_FURNITURE VALUES (101, 'CHR-001', 6);
INSERT INTO PROJECT_FURNITURE VALUES (101, 'TBL-001', 1); 
INSERT INTO PROJECT_FURNITURE VALUES (102, 'CHR-001', 10); 
INSERT INTO PROJECT_FURNITURE VALUES (103, 'SOF-003', 2);
INSERT INTO PROJECT_FURNITURE VALUES (104, 'BED-001', 3);
INSERT INTO PROJECT_FURNITURE VALUES (105, 'DSK-001', 4);
INSERT INTO PROJECT_FURNITURE VALUES (106, 'CAB-001', 2);
INSERT INTO PROJECT_FURNITURE VALUES (101, 'CHR-002', 10);
INSERT INTO PROJECT_FURNITURE VALUES (108, 'LMP-001', 6);
INSERT INTO PROJECT_FURNITURE VALUES (109, 'MIR-001', 8);


INSERT INTO PROJECT_CONTRACTOR VALUES (101, 1, 40.50);
INSERT INTO PROJECT_CONTRACTOR VALUES (101, 2, 35.00); 
INSERT INTO PROJECT_CONTRACTOR VALUES (102, 1, 20.00); 
INSERT INTO PROJECT_CONTRACTOR VALUES (103, 3, 50.00);
INSERT INTO PROJECT_CONTRACTOR VALUES (104, 4, 20.00);
INSERT INTO PROJECT_CONTRACTOR VALUES (105, 5, 80.00);
INSERT INTO PROJECT_CONTRACTOR VALUES (106, 6, 15.50);
INSERT INTO PROJECT_CONTRACTOR VALUES (107, 7, 60.00);
INSERT INTO PROJECT_CONTRACTOR VALUES (108, 8, 25.00);
INSERT INTO PROJECT_CONTRACTOR VALUES (109, 9, 45.00);